name: Build Sonatype release

on:
  release:
    types: [created]

jobs:
  publish-sonatype:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      checks: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 8 #build on JDK 8 for maximum compatibility
          cache: sbt

      - name: Run tests
        env:
          SBT_JUNIT_OUTPUT: ./junit-tests
        run: sbt '+test'

      - name: Release to Sonatype
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        run: |
          ./.github/decodekey.sh
          sbt +ci-release